services:
  app:
    build: .
    container_name: channels_api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 5000:80
    volumes:
      - .:/app



## Docker compose still relies on the docerfile but its replaces some commands as scripted.